Vagrant.configure("2") do |config|
    config.vm.provision "shell", inline: "echo Hello"
  
    config.vm.define "ansible" do |ansible|
      ansible.vm.box = "ubuntu/focal64"
      ansible.vm.network "private_network", ip: "192.168.33.22"
    end
  
    config.vm.define "host" do |host|
      host.vm.box = "ubuntu/focal64"
      host.vm.network "private_network", ip: "192.168.33.23"
      host.vm.network :forwarded_port, host: 8080, guest: 80
      host.vm.network :forwarded_port, host: 8443, guest: 443
    end
  end