VAGRANTFILE_API_VERSION = "2"
Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  # Использовать один и тот же ключ для всех машин
    config.ssh.insert_key = false
    config.vm.define "vagrant1" do |vagrant1|
        vagrant1.vm.box = "ubuntu/focal64"
        vagrant1.vm.network "private_network", ip: "192.168.33.25"
        vagrant1.vm.network "forwarded_port", guest: 80, host: 8080
        vagrant1.vm.network "forwarded_port", guest: 443, host: 8443
    end
    config.vm.define "vagrant2" do |vagrant2|
        vagrant2.vm.network "private_network", ip: "192.168.33.26"
        vagrant2.vm.box = "ubuntu/focal64"
        vagrant2.vm.network "forwarded_port", guest: 80, host: 8081
        vagrant2.vm.network "forwarded_port", guest: 443, host: 8444
    end
    config.vm.define "vagrant3" do |vagrant3|
        vagrant3.vm.network "private_network", ip: "192.168.33.27"
        vagrant3.vm.box = "centos/stream8"
        vagrant3.vm.network "forwarded_port", guest: 80, host: 8082
        vagrant3.vm.network "forwarded_port", guest: 443, host: 8445
    end
    end
